/*

 TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\wicardo\Desktop\gameboy\flappy-boy\assets\bkgs.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tilemapWidth 32
#define tilemapHeight 18
#define tilemapBank 0

extern unsigned char tilemap[];

/* End of TILEMAP.H */
